name: TestUbuntuLatest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10","3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        ./install_dependencies.sh
    - name: tool versions
      run: | 
        iverilog -V | grep -n 1
        verilator --version
        yosys -V
    - name: pip configuration report
      run: |
        pip list
    - name: test
      run: |
        cd ./test
        python ./test.py
